- hosts: 192.168.47.203
  remote_user: root
  tasks:
  - name: copy nginx.conf
    template: src=files/nginx.conf dest=/etc/nginx/nginx.conf
    notify:
    - restart nginx
  - name: copy default.conf
    template: src=files/default.conf dest=/etc/nginx/conf.d/default.conf
    notify:
    - restart nginx
  - name: copy php-fpm conf
    copy: src=files/www.conf dest=/etc/php-fpm.d/www.conf
    notify:
    - restart php-fpm
  handlers:
  - name: restart nginx
    shell: nginx
  - name: restart php-fpm
    service: name=php-fpm state=restarted
